### PR TITLE
Get origin

### PR DESCRIPTION
**Pull request by asajedi**
This gets the right origin for getting the actual collection name
if there are multiple instances of origin.

Resolves GDZ-619 and GDZ-571

### CODE REVIEW

**Comment by asajedi** [comment]
Yes. This is the case. Please have a look at the following url:
https://gdzdev.sub.uni-goettingen.de/id/PPN832902691?origin=/volumes/id/PPN832902683?origin=/collection/mathematica
This happens when you request a multi-volume work from within a collection and then request a document from within this multi-volume work.

**Comment by asajedi** [comment]
Unfortunately, this solution doesn't pass the required collection name for providing the possibility to search in the actual collection.

**Comment by ipf** [comment]
Yes. This is intended, because the origin is not the collection, but the volume. Maybe another solution for the collection problem should be achieved, and the search window really should reflect all collections a work is in.

**Comment by tschaef** [comment]
This URL is invalid and should never have been generated in the first place. Please fix the underlying issue.

**Comment by ipf** [comment]
We close this for now, because we've got a better solution merged in 64d90132c5ddbde6a967be644f5860fa6d409544

**Pull request closed without merging**
